-- ============================================================
-- SETTINGS TABLE FOR ADMIN PANEL
-- Run this in Supabase SQL Editor
-- ============================================================

-- Create settings table
CREATE TABLE IF NOT EXISTS settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW())
);

-- Enable RLS
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Create policies for settings
DROP POLICY IF EXISTS "Allow public read settings" ON settings;
DROP POLICY IF EXISTS "Allow public update settings" ON settings;
DROP POLICY IF EXISTS "Allow public insert settings" ON settings;

CREATE POLICY "Allow public read settings" ON settings FOR SELECT USING (TRUE);
CREATE POLICY "Allow public update settings" ON settings FOR UPDATE USING (TRUE) WITH CHECK (TRUE);
CREATE POLICY "Allow public insert settings" ON settings FOR INSERT WITH CHECK (TRUE);

-- Insert default settings
INSERT INTO settings (key, value) VALUES 
    ('upi_id', '9838272583@okbizaxis'),
    ('admin_username', 'admin'),
    ('admin_password', 'ramrajya2026'),
    ('contact_email', 'info@sreeramrajyamahayagya2026.com')
ON CONFLICT (key) DO NOTHING;

-- Verify
SELECT * FROM settings;
