-- ============================================================
-- श्री राम राज्य महायज्ञ - COMPLETE DATABASE SETUP
-- Run this script in the Supabase SQL Editor
-- ============================================================

-- 1. Create Registrations Table
CREATE TABLE IF NOT EXISTS registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
  member_id TEXT UNIQUE,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  gotra TEXT,
  family_members INT DEFAULT 1,
  city TEXT,
  state TEXT,
  transaction_id TEXT,
  password TEXT,
  payment_status TEXT DEFAULT 'pending',
  prasad BOOLEAN DEFAULT FALSE
);

-- 2. Create Contacts Table
CREATE TABLE IF NOT EXISTS contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  message TEXT,
  type TEXT DEFAULT 'inquiry',
  status TEXT DEFAULT 'new'
);

-- 3. Create Donations Table
CREATE TABLE IF NOT EXISTS donations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
  donor_name TEXT NOT NULL,
  amount NUMERIC DEFAULT 0,
  payment_method TEXT,
  transaction_id TEXT,
  status TEXT DEFAULT 'received'
);

-- 4. Create Sankalp Table (for tracking pledges)
CREATE TABLE IF NOT EXISTS sankalp (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
  user_id BIGINT REFERENCES registrations(id),
  name TEXT NOT NULL,
  father_name TEXT,
  gotra TEXT,
  village TEXT,
  district TEXT,
  state TEXT
);

-- ============================================================
-- ENABLE ROW LEVEL SECURITY
-- ============================================================
ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE sankalp ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- RLS POLICIES FOR REGISTRATIONS
-- ============================================================
-- Drop existing policies if any
DROP POLICY IF EXISTS "Allow public insert registrations" ON registrations;
DROP POLICY IF EXISTS "Allow public read registrations" ON registrations;
DROP POLICY IF EXISTS "Allow public update registrations" ON registrations;
DROP POLICY IF EXISTS "Allow public delete registrations" ON registrations;

-- Create new policies
CREATE POLICY "Allow public insert registrations" ON registrations FOR INSERT WITH CHECK (TRUE);
CREATE POLICY "Allow public read registrations" ON registrations FOR SELECT USING (TRUE);
CREATE POLICY "Allow public update registrations" ON registrations FOR UPDATE USING (TRUE);
CREATE POLICY "Allow public delete registrations" ON registrations FOR DELETE USING (TRUE);

-- ============================================================
-- RLS POLICIES FOR CONTACTS
-- ============================================================
DROP POLICY IF EXISTS "Allow public insert contacts" ON contacts;
DROP POLICY IF EXISTS "Allow public read contacts" ON contacts;
DROP POLICY IF EXISTS "Allow public update contacts" ON contacts;
DROP POLICY IF EXISTS "Allow public delete contacts" ON contacts;

CREATE POLICY "Allow public insert contacts" ON contacts FOR INSERT WITH CHECK (TRUE);
CREATE POLICY "Allow public read contacts" ON contacts FOR SELECT USING (TRUE);
CREATE POLICY "Allow public update contacts" ON contacts FOR UPDATE USING (TRUE);
CREATE POLICY "Allow public delete contacts" ON contacts FOR DELETE USING (TRUE);

-- ============================================================
-- RLS POLICIES FOR DONATIONS
-- ============================================================
DROP POLICY IF EXISTS "Allow public insert donations" ON donations;
DROP POLICY IF EXISTS "Allow public read donations" ON donations;
DROP POLICY IF EXISTS "Allow public update donations" ON donations;
DROP POLICY IF EXISTS "Allow public delete donations" ON donations;

CREATE POLICY "Allow public insert donations" ON donations FOR INSERT WITH CHECK (TRUE);
CREATE POLICY "Allow public read donations" ON donations FOR SELECT USING (TRUE);
CREATE POLICY "Allow public update donations" ON donations FOR UPDATE USING (TRUE);
CREATE POLICY "Allow public delete donations" ON donations FOR DELETE USING (TRUE);

-- ============================================================
-- RLS POLICIES FOR SANKALP
-- ============================================================
DROP POLICY IF EXISTS "Allow public insert sankalp" ON sankalp;
DROP POLICY IF EXISTS "Allow public read sankalp" ON sankalp;

CREATE POLICY "Allow public insert sankalp" ON sankalp FOR INSERT WITH CHECK (TRUE);
CREATE POLICY "Allow public read sankalp" ON sankalp FOR SELECT USING (TRUE);

-- ============================================================
-- INDEXES FOR BETTER PERFORMANCE
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_registrations_phone ON registrations(phone);
CREATE INDEX IF NOT EXISTS idx_registrations_member_id ON registrations(member_id);
CREATE INDEX IF NOT EXISTS idx_registrations_created_at ON registrations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_contacts_created_at ON contacts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_donations_created_at ON donations(created_at DESC);

-- ============================================================
-- FUNCTIONS
-- ============================================================

-- Function to generate unique member ID
CREATE OR REPLACE FUNCTION generate_member_id()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.member_id IS NULL THEN
    NEW.member_id := 'RR-2026-' || LPAD(NEW.id::TEXT, 4, '0');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-generate member ID
DROP TRIGGER IF EXISTS trigger_generate_member_id ON registrations;
CREATE TRIGGER trigger_generate_member_id
  BEFORE INSERT ON registrations
  FOR EACH ROW
  EXECUTE FUNCTION generate_member_id();

-- ============================================================
-- DONE! Database is ready.
-- ============================================================
